# Site settings
title: massiswantoo 
blog_title: massiswantoo
header-img: img/home-bg.jpg
email: massiswantoo@gmail.com
copyright_name: Mas Siswanto
description: "Online Territory of Shikher Verma"
baseurl: "https://massiswanto.github.io/" #base url is for when the site is not at the root but at some subdirectory.
url: https://massiswanto.github.io/ #only used in disque comments for now
disqus_url: shikherverma.com # disque comments are broken if you send http:// along with url
github_username:  massiswantoo
facebook_username:  100009744047212
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
